#!/bin/sh

# PROVIDE: pampfd
# REQUIRE:

. /etc/rc.subr

name="pampfd"
rcvar="pampfd_enable"
command="/usr/local/sbin/${name}"
start_cmd="pampfd_cmd"
start_precmd="pampfd_precmd"
pidfile="/var/run/${name}.pid"

pampfd_socket="/var/run/${name}"
pampfd_whitelist="/usr/local/etc/pampfd.whitelist"

load_rc_config_var $name ${name}_table
load_rc_config_var $name ${name}_host_limit
load_rc_config_var $name ${name}_users_limit

command_args="${pampfd_socket} ${pampfd_table} ${pampfd_whitelist} ${pampfd_host_limit} ${pampfd_users_limit}"

pampfd_precmd()
{
  rm -f "$pampfd_socket"
}

pampfd_cmd()
{
  daemon -p "${pidfile}" "${command}" ${command_args}
}

load_rc_config $name
run_rc_command "$1"
